### ISSUE TITLE
Ignore local development versions

### ISSUE THREAD

**Issue by armordecai** [ogri-la/wowman#114] opened 2020-01-11 10:08 UTC
It would be great if wowman could ignore local development versions of addons, as identified by the presence of any of these things in the addon's folder:

- `.git` folder
- `.hg` folder
- `.svn` folder
- `Version: @project-version@` in the TOC

Right now (I assume) I can't use the "update all" feature because all my local dev copies will get overwritten with the last released version.

Probably these addons should still show in the list to avoid confusion, but not be checked for updates, and wowman should treat them as read-only.

P.S. The new dark theme is working great, thanks!

**Comment by torkus** [comment] 2020-01-11 13:06
This sounds like a very reasonable feature, I'll see that it makes it into the 0.12.0 release, due before end of January.

**Comment by torkus** [comment] 2020-01-11 13:12
> P.S. The new dark theme is working great, thanks!

My pleasure. Thank you for the feedback.

**Comment by torkus** [comment] 2020-01-18 11:47
> Version: @project-version@ in the TOC

@armordecai , can you provide me with an example of this? is it a templating system used by something common?

**Comment by layday** [comment] 2020-01-18 12:11
It's part of Curse's whole pkgmeta thing, see https://authors.curseforge.com/knowledge-base/projects/532-repository-keyword-substitutions.  Add-ons can have a `@project-version@` in their TOC file which the build system will fill in from the VCS.  Unbuilt add-ons are more often than not, not in a usable state.

**Comment by torkus** [comment] 2020-01-18 12:12
cheers, @layday

**Comment by layday** [comment] 2020-01-18 16:47
On my end I chose to ignore symlinks.  Symlinking an add-on they're working on off-site appears to be a common workflow among devs - though I don't suppose any of them actually use instawow.

**Comment by torkus** [comment] 2020-01-18 23:23
Detecting symlinks also seems like a good idea. I'll add it to the list.

> though I don't suppose any of them actually use instawow

It's hard to know these things. My `0.11.0` has seen the most downloads/day but I hear almost nothing about how well it's working (or not). There could just be the same half dozen people downloading it over and over again for all I know ;) Or people try it once, something happens and then they move on. It's a little eerie.

**Comment by layday** [comment] 2020-01-18 23:32
I like to think that the complete lack of issues is testament that instawow is working flawlessly.

*ahem*

**Comment by torkus** [comment] 2020-01-22 12:18
attached is an unreleased version of wowman with features to ignore addons

---
[wowman-0.12.0-unreleased-standalone.jar.zip](https://github.com/ogri-la/wowman/files/4097166/wowman-0.12.0-unreleased-standalone.jar.zip)
sha256: 03d20543b460398f14f3fde1f9170d4e9b703f2d92a475f39a1428ae6a7c582d

---

* it detects addons with SVC directories like .git, .hg etc
* it detects addons with unrendered template .toc files
* it allows you to manually mark an addon as ignored or not. for example, you may want your development version of an addon updated ... 
* addons that are being ignored are greyed out in the gui and you'll get friendly warnings that it's being skipped for updates

**Comment by armordecai** [comment] 2020-01-30 06:00
> attached is an unreleased version of wowman with features to ignore addons

Working great!

One thing I did notice is that the font is different in this version. It seems to be using the Ubuntu font rather than my system default font (Noto Sans, I think), which isn't bad, but it's also using a light weight instead of normal, so it's kind of spindly and harder to read:

![wowman-font](https://user-images.githubusercontent.com/8208500/73423878-3eb03980-42e2-11ea-8f13-239d90822d94.png)

**Comment by torkus** [comment] 2020-01-30 07:25
That's weird - you were using Cinnamon before, right? Did you happen to open wowman after switching out of a Gnome session? There is a process called `gnome-settings-daemon` (I think) that can hang around between sessions and affect everything else.

Could you make sure you've restarted your machine and gone straight into Cinnamon without touching Gnome (if that's how you're working) and check if wowman is still using this font? Because I'm pretty sure I'm not bundling fonts anywhere.

I just confirmed with another user that dark mode in wowman doesn't work in a Gnome desktop because of GTK2 vs GTK3/Gnome-shell weirdness.

**Comment by armordecai** [comment] 2020-01-30 08:42
Cinnamon is the only DE installed on my system, and starts automatically. After rebooting, the font is back to normal. I opened and closed wowman a few times and it stayed normal; I'll post a new issue if I notice it going back to the Ubuntu font (which comes preinstalled in Linux Mint, and I believe was the system default font before I customized it).

**Comment by torkus** [comment] 2020-01-30 08:48
> I'll post a new issue if I notice it going back to the Ubuntu font (which comes preinstalled in Linux Mint, and I believe was the system default font before I customized it).

Please don't file an issue for that, it's not something I can affect. If you do see it happening again, take a look at your process list and make a note of anything like 'settings-daemon' or a specific application you may have started beforehand. 

This happens to me occasionally too because I don't run any DE and have a very plain look and feel. Caja, the fork of Nautilus for the Mate desktop environment used to trigger the launch of Mate's settings daemon, dbus, etc - it was a pain in the neck because all of my fonts would change as well as  look and feel of some apps.

**Comment by torkus** [comment] 2020-02-03 13:32
detection of in-development addons has now been released as part of 0.12.0.

please let me know if you have any problems with it

**Closed by torkus** 2020-02-03 13:32 UTC
Labels: enhancement
